server:
  port:

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/question?useUnicode=true&characterEncoding=utf8
    username:
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.zheye: