server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/question?useUnicode=true&characterEncoding=utf8
    username: root
    password: javafan199612
    driverClassName: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.zheye: debug